### ISSUE TITLE
Updated release for spark-1.5.1-bin-hadoop2.6?

### ISSUE THREAD

**Issue by mharisce** [tuplejump/calliope#46]
Can someone please provide its update for spark-1.5.1-bin-hadoop2.6? I am following instructions here http://tuplejump.github.io/calliope/calliope-server.html but i am stuck.

Issue is with Spark Hive Version. I am getting NoSuchMethodException exceptions.

**Comment by espiegel** [comment]
Same. I'm getting the following stack trace when running with spark 1.6.0:

Exception in thread "main" java.lang.NoSuchMethodException: org.apache.hadoop.hive.conf.HiveConf.getTimeVar(org.apache.hadoop.hive.conf.HiveConf$ConfVars, java.util.concurrent.TimeUnit)
    at java.lang.Class.getMethod(Class.java:1778)
    at org.apache.spark.sql.hive.client.Shim.findMethod(HiveShim.scala:114)
    at org.apache.spark.sql.hive.client.Shim_v0_14.getTimeVarMethod$lzycompute(HiveShim.scala:416)
    at org.apache.spark.sql.hive.client.Shim_v0_14.getTimeVarMethod(HiveShim.scala:415)
    at org.apache.spark.sql.hive.client.Shim_v0_14.getMetastoreClientConnectRetryDelayMillis(HiveShim.scala:460)
    at org.apache.spark.sql.hive.client.ClientWrapper.<init>(ClientWrapper.scala:213)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.apache.spark.sql.hive.client.IsolatedClientLoader.createClient(IsolatedClientLoader.scala:249)
    at org.apache.spark.sql.hive.HiveContext.metadataHive$lzycompute(HiveContext.scala:327)
    at org.apache.spark.sql.hive.HiveContext.metadataHive(HiveContext.scala:237)
    at org.apache.spark.sql.hive.HiveContext.setConf(HiveContext.scala:441)
    at org.apache.spark.sql.hive.HiveContext.defaultOverrides(HiveContext.scala:226)
    at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:229)
    at org.apache.spark.sql.hive.HiveContext.<init>(HiveContext.scala:101)
    at org.apache.spark.sql.hive.CassandraAwareHiveContext.<init>(CassandraAwareHiveContext.scala:28)
    at com.tuplejump.calliope.server.CalliopeSparkSQLEnv$$anon$1.<init>(CalliopeSparkSQLEnv.scala:29)
    at com.tuplejump.calliope.server.CalliopeSparkSQLEnv$.init(CalliopeSparkSQLEnv.scala:29)
    at com.tuplejump.calliope.server.CalliopeServer2$.main(CalliopeServer2.scala:40)
    at com.tuplejump.calliope.server.CalliopeServer2.main(CalliopeServer2.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

**Comment by mharisce** [comment]
@espiegel if you are trying to bridge cassandra, spark sql over jdbc u can use other project in my github repos. that works! just uncomment the configurations in the code
